services:
  - type: web
    name: laas
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: SECRET_KEY
        generateValue: true
      - key: DEFAULT_ADMIN_EMAIL
        value: admin@example.com
      - key: DEFAULT_ADMIN_PASSWORD
        sync: false
      - key: DEFAULT_ADMIN_NAME
        value: System Admin
